DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `createdDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastModifiedDate` DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP, 
  PRIMARY KEY (id),
  UNIQUE KEY (email)
);